apiVersion: v2
name: theft-data
description: Data stores for the theft-detection-platform services
type: application
version: 0.1.0
appVersion: "0.1.0"
kubeVersion: ">=1.37.0-0"
sources:
  - https://github.com/Nizar7kabbaj/theft-detection-platform
maintainers:
  - name: Nizar Kabbaj
