redis:
  instances:
    redis-stream:
      resources:
        requests:
          cpu: 25m
          memory: 384Mi
        limits:
          memory: 384Mi
      extraArgs:
        - --maxmemory
        - 256mb

networkPolicy:
  apiServer:
    cidr: 172.19.0.0/16
