/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/cameras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cameras */
        get: operations["list_cameras_api_v1_cameras_get"];
        put?: never;
        /** Create Camera */
        post: operations["create_camera_api_v1_cameras_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cameras/{camera_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Camera */
        get: operations["get_camera_api_v1_cameras__camera_id__get"];
        put?: never;
        post?: never;
        /** Delete Camera */
        delete: operations["delete_camera_api_v1_cameras__camera_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/detections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Detections */
        get: operations["list_detections_api_v1_detections_get"];
        put?: never;
        /** Create Detection */
        post: operations["create_detection_api_v1_detections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/detections/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Frame */
        post: operations["analyze_frame_api_v1_detections_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/detections/session/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Detections By Session */
        get: operations["list_detections_by_session_api_v1_detections_session__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/detections/{detection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Detection */
        delete: operations["delete_detection_api_v1_detections__detection_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Alerts */
        get: operations["list_alerts_api_v1_alerts_get"];
        put?: never;
        /** Create Alert */
        post: operations["create_alert_api_v1_alerts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/cameras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Alert Cameras */
        get: operations["list_alert_cameras_api_v1_alerts_cameras_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{alert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Alert */
        get: operations["get_alert_api_v1_alerts__alert_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{alert_id}/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Alert Snapshot */
        get: operations["get_alert_snapshot_api_v1_alerts__alert_id__snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{alert_id}/clip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Alert Clip */
        get: operations["get_alert_clip_api_v1_alerts__alert_id__clip_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{alert_id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Acknowledge Alert */
        patch: operations["acknowledge_alert_api_v1_alerts__alert_id__acknowledge_patch"];
        trace?: never;
    };
    "/api/v1/alerts/{alert_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Decide Alert */
        patch: operations["decide_alert_api_v1_alerts__alert_id__decision_patch"];
        trace?: never;
    };
    "/api/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["get_stats_api_v1_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/timeseries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats Timeseries */
        get: operations["get_stats_timeseries_api_v1_stats_timeseries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get System Stats */
        get: operations["get_system_stats_api_v1_stats_system_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/system/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get System History */
        get: operations["get_system_history_api_v1_stats_system_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/edge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Edge Stats */
        get: operations["get_edge_stats_api_v1_stats_edge_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Identity */
        get: operations["read_identity_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policy/detection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Policy */
        get: operations["read_policy_api_v1_policy_detection_get"];
        /** Update Policy */
        put: operations["update_policy_api_v1_policy_detection_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policy/detection/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Policy History */
        get: operations["read_policy_history_api_v1_policy_detection_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/permissions/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Role Permissions */
        get: operations["get_role_permissions_api_v1_permissions_roles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertBucket */
        AlertBucket: {
            /**
             * Bucket
             * Format: date-time
             */
            bucket: string;
            /** Critical */
            critical: number;
            /** Warning */
            warning: number;
            /** Notice */
            notice: number;
            /** Info */
            info: number;
            /** Unspecified */
            unspecified: number;
            /** Total */
            total: number;
        };
        /** AlertCreate */
        AlertCreate: {
            /** Alert Id */
            alert_id: string;
            /** Session Id */
            session_id: number;
            /** Frame Index */
            frame_index: number;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Camera Id
             * @default default
             */
            camera_id: string | null;
            person?: components["schemas"]["Person"] | null;
            object?: components["schemas"]["Object"] | null;
            severity: components["schemas"]["Severity"];
            /** Snapshot Path */
            snapshot_path?: string | null;
            /** Clip Path */
            clip_path?: string | null;
            /** @default ALERT_TYPE_OBJECT_PROXIMITY */
            alert_type: components["schemas"]["AlertType"];
            /** Frame Width */
            frame_width?: number | null;
            /** Frame Height */
            frame_height?: number | null;
            concealment?: components["schemas"]["Concealment"] | null;
            /** Classifier Score */
            classifier_score?: number | null;
            /** Classifier State */
            classifier_state?: string | null;
        };
        /** AlertDetail */
        AlertDetail: {
            /** Id */
            _id: string;
            /** Alert Id */
            alert_id: string;
            /** Session Id */
            session_id: number;
            /** Frame Index */
            frame_index: number;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Camera Id */
            camera_id: string;
            severity: components["schemas"]["Severity"];
            alert_type?: components["schemas"]["AlertType"] | null;
            /**
             * Acknowledged
             * @default false
             */
            acknowledged: boolean;
            /** Acknowledged At */
            acknowledged_at?: string | null;
            /** @default DECISION_UNSPECIFIED */
            decision: components["schemas"]["Decision"];
            /** Decided At */
            decided_at?: string | null;
            /** Decided By */
            decided_by?: string | null;
            person?: components["schemas"]["Person"] | null;
            object?: components["schemas"]["Object"] | null;
            /** Frame Width */
            frame_width?: number | null;
            /** Frame Height */
            frame_height?: number | null;
            concealment?: components["schemas"]["Concealment"] | null;
            /** Classifier Score */
            classifier_score?: number | null;
            /** Classifier State */
            classifier_state?: string | null;
            /** Snapshot Url */
            snapshot_url?: string | null;
            /** Clip Url */
            clip_url?: string | null;
            /**
             * Dispatch Failed
             * @default false
             */
            dispatch_failed: boolean;
            delivery?: components["schemas"]["DeliveryStatusView"] | null;
        };
        /** AlertPage */
        AlertPage: {
            /** Items */
            items: components["schemas"]["AlertResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** AlertResponse */
        AlertResponse: {
            /** Id */
            _id: string;
            /** Alert Id */
            alert_id: string;
            /** Session Id */
            session_id: number;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Camera Id */
            camera_id: string;
            severity: components["schemas"]["Severity"];
            /** Object Name */
            object_name: string;
            /** Confidence */
            confidence?: number | null;
            /** Snapshot Url */
            snapshot_url?: string | null;
            alert_type?: components["schemas"]["AlertType"] | null;
            /**
             * Acknowledged
             * @default false
             */
            acknowledged: boolean;
            /** Acknowledged At */
            acknowledged_at?: string | null;
            /** @default DECISION_UNSPECIFIED */
            decision: components["schemas"]["Decision"];
            /** Decided At */
            decided_at?: string | null;
            /** Decided By */
            decided_by?: string | null;
            /**
             * Dispatch Failed
             * @default false
             */
            dispatch_failed: boolean;
            delivery?: components["schemas"]["DeliverySummary"] | null;
        };
        /**
         * AlertSort
         * @enum {string}
         */
        AlertSort: "created_at" | "decided_at";
        /**
         * AlertType
         * @enum {string}
         */
        AlertType: "ALERT_TYPE_UNSPECIFIED" | "ALERT_TYPE_OBJECT_PROXIMITY" | "ALERT_TYPE_CONCEALMENT" | "ALERT_TYPE_LOITERING";
        /** Bbox */
        Bbox: {
            /** X1 */
            x1: number;
            /** Y1 */
            y1: number;
            /** X2 */
            x2: number;
            /** Y2 */
            y2: number;
        };
        /** Body_analyze_frame_api_v1_detections_analyze_post */
        Body_analyze_frame_api_v1_detections_analyze_post: {
            /** Session Id */
            session_id: number;
            /** Frame Index */
            frame_index: number;
            /**
             * Camera Id
             * @default default
             */
            camera_id: string;
            /** File */
            file: string;
        };
        /**
         * BucketUnit
         * @enum {string}
         */
        BucketUnit: "hour" | "day";
        /** CameraCreate */
        CameraCreate: {
            /** Camera Id */
            camera_id: string;
            /** Name */
            name: string;
            /** Location */
            location: string;
            /** Stream Url */
            stream_url?: string | null;
            /**
             * Status
             * @default active
             */
            status: string;
        };
        /** CameraHealthView */
        CameraHealthView: {
            /** @default unknown */
            state: components["schemas"]["HealthState"];
            /** Last Frame At */
            last_frame_at?: string | null;
            /** Age Seconds */
            age_seconds?: number | null;
        };
        /** CameraResponse */
        CameraResponse: {
            /** Id */
            _id: string;
            /** Camera Id */
            camera_id: string;
            /** Name */
            name: string;
            /** Location */
            location: string;
            /** Stream Url */
            stream_url?: string | null;
            /** Status */
            status: string;
            health?: components["schemas"]["CameraHealthView"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ClassifierPolicy */
        ClassifierPolicy: {
            /**
             * Anomaly Threshold
             * @default 0.6
             */
            anomaly_threshold: number;
            /**
             * Person Confidence
             * @default 0.7
             */
            person_confidence: number;
            /**
             * Object Confidence
             * @default 0.35
             */
            object_confidence: number;
        };
        /** Concealment */
        Concealment: {
            /** Object Track Id */
            object_track_id: number;
            /** Object Class */
            object_class: string;
            /** Last Seen Frame */
            last_seen_frame: number;
            /** Missing Frames */
            missing_frames: number;
            /** Person Track Id */
            person_track_id: number;
            /** Wrist Index */
            wrist_index: number;
            /** Wrist X */
            wrist_x: number;
            /** Wrist Y */
            wrist_y: number;
            /** Grab Distance */
            grab_distance: number;
        };
        /** ConcealmentPolicy */
        ConcealmentPolicy: {
            /**
             * Grab Ratio
             * @default 0.6
             */
            grab_ratio: number;
            /**
             * Missing Seconds
             * @default 1
             */
            missing_seconds: number;
            /**
             * Keypoint Confidence
             * @default 0.5
             */
            keypoint_confidence: number;
            /**
             * Expiry Seconds
             * @default 10
             */
            expiry_seconds: number;
        };
        /**
         * Decision
         * @enum {string}
         */
        Decision: "DECISION_UNSPECIFIED" | "DECISION_CONFIRMED" | "DECISION_DISMISSED" | "DECISION_UNSURE";
        /** DecisionBucket */
        DecisionBucket: {
            /**
             * Bucket
             * Format: date-time
             */
            bucket: string;
            /** Confirmed */
            confirmed: number;
            /** Dismissed */
            dismissed: number;
            /** Unsure */
            unsure: number;
            /** Total */
            total: number;
        };
        /** DecisionUpdate */
        DecisionUpdate: {
            decision: components["schemas"]["Decision"];
        };
        /** DeliveryRecord */
        DeliveryRecord: {
            /** Channel */
            channel: string;
            /** Recipient */
            recipient: string;
            state: components["schemas"]["DeliveryState"];
            /** Attempts */
            attempts: number;
            /** Requeue Count */
            requeue_count: number;
            /** Last Error Class */
            last_error_class?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * DeliveryState
         * @enum {string}
         */
        DeliveryState: "unknown" | "pending" | "sending" | "sent" | "failed" | "dead" | "buffered";
        /** DeliveryStatusView */
        DeliveryStatusView: {
            /** Known */
            known: boolean;
            /** Records */
            records: components["schemas"]["DeliveryRecord"][];
        };
        /** DeliverySummary */
        DeliverySummary: {
            /** Known */
            known: boolean;
            state: components["schemas"]["DeliveryState"];
            /** Attempts */
            attempts: number;
        };
        /** DetectionCreate */
        DetectionCreate: {
            /** Session Id */
            session_id: number;
            /** Frame Index */
            frame_index: number;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Camera Id
             * @default default
             */
            camera_id: string | null;
            /** Class Name */
            class_name: string;
            /** Confidence */
            confidence: number;
            bbox: components["schemas"]["Bbox"];
            /** Keypoints */
            keypoints?: components["schemas"]["app__schemas__common__Keypoint"][] | null;
            /**
             * Track Id
             * @default 0
             */
            track_id: number;
            /**
             * Detection Present
             * @default false
             */
            detection_present: boolean;
        };
        /** DetectionResponse */
        DetectionResponse: {
            /** Id */
            _id: string;
            /** Session Id */
            session_id: number;
            /** Frame Index */
            frame_index: number;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Camera Id */
            camera_id: string;
            /** Class Name */
            class_name: string;
            /** Confidence */
            confidence: number;
            bbox: components["schemas"]["Bbox"];
            /** Keypoints */
            keypoints?: components["schemas"]["app__schemas__common__Keypoint"][] | null;
            /** Track Id */
            track_id: number;
            /** Detection Present */
            detection_present: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** EdgeStatsResponse */
        EdgeStatsResponse: {
            /** Average Fps */
            average_fps: number | null;
            /** Latency Ms */
            latency_ms: number | null;
            /** Gpu Temperature C */
            gpu_temperature_c: number | null;
            /** Gpu Name */
            gpu_name: string | null;
            /** Reporting Cameras */
            reporting_cameras: number;
            /** Total Cameras */
            total_cameras: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthState
         * @enum {string}
         */
        HealthState: "online" | "degraded" | "offline" | "unknown";
        /** IdentityResponse */
        IdentityResponse: {
            /** User Id */
            user_id: string;
            /** Username */
            username: string;
            /** Roles */
            roles: string[];
            /** Permissions */
            permissions: components["schemas"]["Permission"][];
        };
        /** Object */
        Object: {
            /** Class Name */
            class_name: string;
            bbox?: components["schemas"]["Bbox"] | null;
        };
        /**
         * Permission
         * @enum {string}
         */
        Permission: "camera:read" | "camera:write" | "detection:read" | "detection:write" | "detection:infer" | "alert:read" | "alert:write" | "alert:acknowledge" | "stats:read" | "audit:query" | "settings:read" | "settings:write" | "user:read" | "user:write";
        /** Person */
        Person: {
            /**
             * Track Id
             * @default 0
             */
            track_id: number;
            bbox?: components["schemas"]["Bbox"] | null;
            /** Keypoints */
            keypoints?: components["schemas"]["app__schemas__alert__Keypoint"][];
        };
        /** PolicyChange */
        PolicyChange: {
            /** Field Name */
            field_name: string;
            /** Previous */
            previous: number;
            /** Current */
            current: number;
        };
        /** PolicyPayload */
        PolicyPayload: {
            concealment?: components["schemas"]["ConcealmentPolicy"];
            classifier?: components["schemas"]["ClassifierPolicy"];
        };
        /** PolicyResponse */
        PolicyResponse: {
            /** Version */
            version: number;
            policy: components["schemas"]["PolicyPayload"];
            /** Changed By */
            changed_by: string;
            /**
             * Changed At
             * Format: date-time
             */
            changed_at: string;
            runtime?: components["schemas"]["PolicyRuntime"];
        };
        /** PolicyRevision */
        PolicyRevision: {
            /** Version */
            version: number;
            /** Changed By */
            changed_by: string;
            /**
             * Changed At
             * Format: date-time
             */
            changed_at: string;
            /** Changes */
            changes: components["schemas"]["PolicyChange"][];
        };
        /** PolicyRuntime */
        PolicyRuntime: {
            /** Version */
            version?: number | null;
            /** Applied At */
            applied_at?: string | null;
            /** Device */
            device?: string | null;
        };
        /** PolicyUpdate */
        PolicyUpdate: {
            /** Expected Version */
            expected_version: number;
            policy: components["schemas"]["PolicyPayload"];
        };
        /** RolePermissionMap */
        RolePermissionMap: {
            /** Permissions */
            permissions: string[];
            /** Roles */
            roles: {
                [key: string]: string[];
            };
        };
        /** ServiceMemory */
        ServiceMemory: {
            /** Camera */
            camera: number | null;
            /** Gate */
            gate: number | null;
            /** Inference */
            inference: number | null;
            /** Notification */
            notification: number | null;
        };
        /**
         * Severity
         * @enum {string}
         */
        Severity: "SEVERITY_UNSPECIFIED" | "SEVERITY_INFO" | "SEVERITY_NOTICE" | "SEVERITY_WARNING" | "SEVERITY_CRITICAL";
        /** StatsResponse */
        StatsResponse: {
            /** Total Alerts */
            total_alerts: number;
            /** Total Detections */
            total_detections: number;
            /** Total Cameras */
            total_cameras: number;
            /** Alerts Today */
            alerts_today: number;
            /** High Severity */
            high_severity: number;
            /** Medium Severity */
            medium_severity: number;
            /** Top Objects */
            top_objects: components["schemas"]["TopObject"][];
        };
        /** StatsTimeseriesResponse */
        StatsTimeseriesResponse: {
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            unit: components["schemas"]["BucketUnit"];
            /** Alerts */
            alerts: components["schemas"]["AlertBucket"][];
            /** Decisions */
            decisions: components["schemas"]["DecisionBucket"][];
        };
        /** SystemHistoryResponse */
        SystemHistoryResponse: {
            /** Cpu */
            cpu: number[];
            /** Gpu */
            gpu: number[];
            /** Memory */
            memory: number[];
            /** Network */
            network: number[];
            /** Cpu Temperature */
            cpu_temperature: number[];
            /** Gpu Temperature */
            gpu_temperature: number[];
        };
        /** SystemStatsResponse */
        SystemStatsResponse: {
            /** Cpu Percent */
            cpu_percent: number | null;
            /** Memory Percent */
            memory_percent: number | null;
            /** Network Bytes Per Second */
            network_bytes_per_second: number | null;
            /** Gpu Percent */
            gpu_percent: number | null;
            /** Gpu Temperature C */
            gpu_temperature_c: number | null;
            /** Cpu Temperature C */
            cpu_temperature_c: number | null;
            service_memory_bytes: components["schemas"]["ServiceMemory"];
        };
        /** TopObject */
        TopObject: {
            /** Object */
            object: string | null;
            /** Count */
            count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Keypoint */
        app__schemas__alert__Keypoint: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Confidence */
            confidence: number;
        };
        /** Keypoint */
        app__schemas__common__Keypoint: {
            /** Name */
            name?: string | null;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Confidence */
            confidence: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_cameras_api_v1_cameras_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraResponse"][];
                };
            };
        };
    };
    create_camera_api_v1_cameras_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CameraCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_camera_api_v1_cameras__camera_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_camera_api_v1_cameras__camera_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_detections_api_v1_detections_get: {
        parameters: {
            query?: {
                limit?: number;
                skip?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_detection_api_v1_detections_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DetectionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_frame_api_v1_detections_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_frame_api_v1_detections_analyze_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_detections_by_session_api_v1_detections_session__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_detection_api_v1_detections__detection_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                detection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alerts_api_v1_alerts_get: {
        parameters: {
            query?: {
                severity?: components["schemas"]["Severity"] | null;
                acknowledged?: boolean | null;
                decision?: components["schemas"]["Decision"] | null;
                camera_id?: string | null;
                sort?: components["schemas"]["AlertSort"];
                limit?: number;
                cursor?: string | null;
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_alert_api_v1_alerts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alert_cameras_api_v1_alerts_cameras_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    get_alert_api_v1_alerts__alert_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_alert_snapshot_api_v1_alerts__alert_id__snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_alert_clip_api_v1_alerts__alert_id__clip_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acknowledge_alert_api_v1_alerts__alert_id__acknowledge_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_alert_api_v1_alerts__alert_id__decision_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_api_v1_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
        };
    };
    get_stats_timeseries_api_v1_stats_timeseries_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                unit?: components["schemas"]["BucketUnit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsTimeseriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_system_stats_api_v1_stats_system_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatsResponse"];
                };
            };
        };
    };
    get_system_history_api_v1_stats_system_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemHistoryResponse"];
                };
            };
        };
    };
    get_edge_stats_api_v1_stats_edge_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EdgeStatsResponse"];
                };
            };
        };
    };
    read_identity_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityResponse"];
                };
            };
        };
    };
    read_policy_api_v1_policy_detection_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyResponse"];
                };
            };
        };
    };
    update_policy_api_v1_policy_detection_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_policy_history_api_v1_policy_detection_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyRevision"][];
                };
            };
        };
    };
    get_role_permissions_api_v1_permissions_roles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolePermissionMap"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
