/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/cameras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cameras */
        get: operations["list_cameras_api_v1_cameras_get"];
        put?: never;
        /** Create Camera */
        post: operations["create_camera_api_v1_cameras_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cameras/{camera_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Camera */
        get: operations["get_camera_api_v1_cameras__camera_id__get"];
        put?: never;
        post?: never;
        /** Delete Camera */
        delete: operations["delete_camera_api_v1_cameras__camera_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/detections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Detections */
        get: operations["list_detections_api_v1_detections_get"];
        put?: never;
        /** Create Detection */
        post: operations["create_detection_api_v1_detections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/detections/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Frame */
        post: operations["analyze_frame_api_v1_detections_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/detections/session/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Detections By Session */
        get: operations["list_detections_by_session_api_v1_detections_session__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/detections/{detection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Detection */
        delete: operations["delete_detection_api_v1_detections__detection_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Alerts */
        get: operations["list_alerts_api_v1_alerts_get"];
        put?: never;
        /** Create Alert */
        post: operations["create_alert_api_v1_alerts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{alert_id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Acknowledge Alert */
        patch: operations["acknowledge_alert_api_v1_alerts__alert_id__acknowledge_patch"];
        trace?: never;
    };
    "/api/v1/alerts/{alert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Alert */
        delete: operations["delete_alert_api_v1_alerts__alert_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["get_stats_api_v1_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertCreate */
        AlertCreate: {
            /** Alert Id */
            alert_id: string;
            /** Session Id */
            session_id: number;
            /** Frame Index */
            frame_index: number;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Camera Id
             * @default default
             */
            camera_id: string | null;
            person?: components["schemas"]["Person"] | null;
            object?: components["schemas"]["Object"] | null;
            severity: components["schemas"]["Severity"];
            /** Snapshot Path */
            snapshot_path?: string | null;
            /** @default ALERT_TYPE_OBJECT_PROXIMITY */
            alert_type: components["schemas"]["AlertType"];
        };
        /** AlertResponse */
        AlertResponse: {
            /** Id */
            _id: string;
            /** Alert Id */
            alert_id: string;
            /** Session Id */
            session_id: number;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Camera Id */
            camera_id: string;
            severity: components["schemas"]["Severity"];
            /** Object Name */
            object_name: string;
            /** Confidence */
            confidence?: number | null;
            /** Snapshot Url */
            snapshot_url?: string | null;
            alert_type?: components["schemas"]["AlertType"] | null;
        };
        /**
         * AlertType
         * @enum {string}
         */
        AlertType: "ALERT_TYPE_UNSPECIFIED" | "ALERT_TYPE_OBJECT_PROXIMITY" | "ALERT_TYPE_BENDING" | "ALERT_TYPE_LOITERING";
        /** Bbox */
        Bbox: {
            /** X1 */
            x1: number;
            /** Y1 */
            y1: number;
            /** X2 */
            x2: number;
            /** Y2 */
            y2: number;
        };
        /** Body_analyze_frame_api_v1_detections_analyze_post */
        Body_analyze_frame_api_v1_detections_analyze_post: {
            /** Session Id */
            session_id: number;
            /** Frame Index */
            frame_index: number;
            /**
             * Camera Id
             * @default default
             */
            camera_id: string;
            /** File */
            file: string;
        };
        /** CameraCreate */
        CameraCreate: {
            /** Name */
            name: string;
            /** Location */
            location: string;
            /** Stream Url */
            stream_url?: string | null;
            /**
             * Status
             * @default active
             */
            status: string;
        };
        /** CameraResponse */
        CameraResponse: {
            /** Id */
            _id: string;
            /** Name */
            name: string;
            /** Location */
            location: string;
            /** Stream Url */
            stream_url?: string | null;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** DetectionCreate */
        DetectionCreate: {
            /** Session Id */
            session_id: number;
            /** Frame Index */
            frame_index: number;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Camera Id
             * @default default
             */
            camera_id: string | null;
            /** Class Name */
            class_name: string;
            /** Confidence */
            confidence: number;
            bbox: components["schemas"]["Bbox"];
            /** Keypoints */
            keypoints?: components["schemas"]["app__schemas__common__Keypoint"][] | null;
            /**
             * Track Id
             * @default 0
             */
            track_id: number;
            /**
             * Detection Present
             * @default false
             */
            detection_present: boolean;
        };
        /** DetectionResponse */
        DetectionResponse: {
            /** Id */
            _id: string;
            /** Session Id */
            session_id: number;
            /** Frame Index */
            frame_index: number;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Camera Id */
            camera_id: string;
            /** Class Name */
            class_name: string;
            /** Confidence */
            confidence: number;
            bbox: components["schemas"]["Bbox"];
            /** Keypoints */
            keypoints?: components["schemas"]["Keypoint-Output"][] | null;
            /** Track Id */
            track_id: number;
            /** Detection Present */
            detection_present: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Keypoint */
        "Keypoint-Output": {
            /** Name */
            name?: string | null;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Confidence */
            confidence: number;
        };
        /** Object */
        Object: {
            /** Class Name */
            class_name: string;
            bbox?: components["schemas"]["Bbox"] | null;
        };
        /** Person */
        Person: {
            /**
             * Track Id
             * @default 0
             */
            track_id: number;
            bbox?: components["schemas"]["Bbox"] | null;
            /** Keypoints */
            keypoints?: components["schemas"]["app__schemas__alert__Keypoint"][];
        };
        /**
         * Severity
         * @enum {string}
         */
        Severity: "SEVERITY_UNSPECIFIED" | "SEVERITY_INFO" | "SEVERITY_NOTICE" | "SEVERITY_WARNING" | "SEVERITY_CRITICAL";
        /** StatsResponse */
        StatsResponse: {
            /** Total Alerts */
            total_alerts: number;
            /** Total Detections */
            total_detections: number;
            /** Total Cameras */
            total_cameras: number;
            /** Alerts Today */
            alerts_today: number;
            /** High Severity */
            high_severity: number;
            /** Medium Severity */
            medium_severity: number;
            /** Top Objects */
            top_objects: components["schemas"]["TopObject"][];
        };
        /** TopObject */
        TopObject: {
            /** Object */
            object: string | null;
            /** Count */
            count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Keypoint */
        app__schemas__alert__Keypoint: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Confidence */
            confidence: number;
        };
        /** Keypoint */
        app__schemas__common__Keypoint: {
            /** Name */
            name?: string | null;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Confidence */
            confidence: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_cameras_api_v1_cameras_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraResponse"][];
                };
            };
        };
    };
    create_camera_api_v1_cameras_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CameraCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_camera_api_v1_cameras__camera_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_camera_api_v1_cameras__camera_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_detections_api_v1_detections_get: {
        parameters: {
            query?: {
                limit?: number;
                skip?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_detection_api_v1_detections_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DetectionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_frame_api_v1_detections_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_frame_api_v1_detections_analyze_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_detections_by_session_api_v1_detections_session__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_detection_api_v1_detections__detection_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                detection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alerts_api_v1_alerts_get: {
        parameters: {
            query?: {
                severity?: components["schemas"]["Severity"] | null;
                limit?: number;
                skip?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_alert_api_v1_alerts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acknowledge_alert_api_v1_alerts__alert_id__acknowledge_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_alert_api_v1_alerts__alert_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_api_v1_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
