repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.0
    hooks:
      - id: terraform_fmt

      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl

      - id: terraform_tfsec
        args:
          - --args=--config-file=__GIT_WORKING_DIR__/.tfsec/config.yml

  - repo: https://github.com/bridgecrewio/checkov
    rev: 3.2.530
    hooks:
      - id: checkov
        args:
          - --quiet
          - --compact
          - --framework
          - terraform
          - --directory
          - infrastructure/terraform
          - --config-file
          - .checkov.yaml

  - repo: local
    hooks:
      - id: conftest
        name: conftest opa policies against terraform plan
        entry: conftest test --policy infrastructure/terraform/policies/opa
        language: system
        stages: [manual]
        pass_filenames: true
        files: \.json$