apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: cnpg-system
  labels:
    app.kubernetes.io/part-of: theft-detection-platform
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cnpg-operator
  namespace: cnpg-system
  labels:
    app.kubernetes.io/part-of: theft-detection-platform
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: cloudnative-pg
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - ipBlock:
            cidr: __CONTROL_PLANE_IP__/32
        - ipBlock:
            cidr: 169.254.7.127/32
      ports:
        - port: 9443
          protocol: TCP
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    - to:
        - ipBlock:
            cidr: __CONTROL_PLANE_IP__/32
      ports:
        - port: 6443
          protocol: TCP
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: theft
          podSelector:
            matchLabels:
              cnpg.io/cluster: postgres
      ports:
        - port: 8000
          protocol: TCP
        - port: 15008
          protocol: TCP
