# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x11theftdetection.v1\"6\n\x04\x42\x62ox\x12\n\n\x02x1\x18\x01 \x01(\x02\x12\n\n\x02y1\x18\x02 \x01(\x02\x12\n\n\x02x2\x18\x03 \x01(\x02\x12\n\n\x02y2\x18\x04 \x01(\x02\"4\n\x08Keypoint\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\x12\n\nconfidence\x18\x03 \x01(\x02\"q\n\x06Person\x12\x10\n\x08track_id\x18\x01 \x01(\x05\x12%\n\x04\x62\x62ox\x18\x02 \x01(\x0b\x32\x17.theftdetection.v1.Bbox\x12.\n\tkeypoints\x18\x03 \x03(\x0b\x32\x1b.theftdetection.v1.Keypoint\"C\n\x06Object\x12\x12\n\nclass_name\x18\x01 \x01(\t\x12%\n\x04\x62\x62ox\x18\x02 \x01(\x0b\x32\x17.theftdetection.v1.Bbox*y\n\x08Severity\x12\x18\n\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x11\n\rSEVERITY_INFO\x10\x01\x12\x13\n\x0fSEVERITY_NOTICE\x10\x02\x12\x14\n\x10SEVERITY_WARNING\x10\x03\x12\x15\n\x11SEVERITY_CRITICAL\x10\x04*z\n\tAlertType\x12\x1a\n\x16\x41LERT_TYPE_UNSPECIFIED\x10\x00\x12\x1f\n\x1b\x41LERT_TYPE_OBJECT_PROXIMITY\x10\x01\x12\x16\n\x12\x41LERT_TYPE_BENDING\x10\x02\x12\x18\n\x14\x41LERT_TYPE_LOITERING\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEVERITY']._serialized_start=329
  _globals['_SEVERITY']._serialized_end=450
  _globals['_ALERTTYPE']._serialized_start=452
  _globals['_ALERTTYPE']._serialized_end=574
  _globals['_BBOX']._serialized_start=35
  _globals['_BBOX']._serialized_end=89
  _globals['_KEYPOINT']._serialized_start=91
  _globals['_KEYPOINT']._serialized_end=143
  _globals['_PERSON']._serialized_start=145
  _globals['_PERSON']._serialized_end=258
  _globals['_OBJECT']._serialized_start=260
  _globals['_OBJECT']._serialized_end=327
# @@protoc_insertion_point(module_scope)
