# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: decision.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'decision.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x65\x63ision.proto\x12\x11theftdetection.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0c\x63ommon.proto\"o\n\x12\x44\x65\x63ideAlertRequest\x12\x10\n\x08\x61lert_id\x18\x01 \x01(\t\x12-\n\x08\x64\x65\x63ision\x18\x02 \x01(\x0e\x32\x1b.theftdetection.v1.Decision\x12\x18\n\x10telegram_user_id\x18\x03 \x01(\x03\"\xb8\x01\n\x10\x44\x65\x63ideAlertReply\x12\x31\n\x07outcome\x18\x01 \x01(\x0e\x32 .theftdetection.v1.DecideOutcome\x12-\n\x08\x64\x65\x63ision\x18\x02 \x01(\x0e\x32\x1b.theftdetection.v1.Decision\x12\x12\n\ndecided_by\x18\x03 \x01(\t\x12.\n\ndecided_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp*\xdf\x01\n\rDecideOutcome\x12\x1e\n\x1a\x44\x45\x43IDE_OUTCOME_UNSPECIFIED\x10\x00\x12\x1a\n\x16\x44\x45\x43IDE_OUTCOME_DECIDED\x10\x01\x12\"\n\x1e\x44\x45\x43IDE_OUTCOME_ALREADY_DECIDED\x10\x02\x12\"\n\x1e\x44\x45\x43IDE_OUTCOME_ALERT_NOT_FOUND\x10\x03\x12#\n\x1f\x44\x45\x43IDE_OUTCOME_OPERATOR_UNKNOWN\x10\x04\x12%\n!DECIDE_OUTCOME_OPERATOR_FORBIDDEN\x10\x05\x32q\n\x14\x41lertDecisionService\x12Y\n\x0b\x44\x65\x63ideAlert\x12%.theftdetection.v1.DecideAlertRequest\x1a#.theftdetection.v1.DecideAlertReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'decision_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DECIDEOUTCOME']._serialized_start=385
  _globals['_DECIDEOUTCOME']._serialized_end=608
  _globals['_DECIDEALERTREQUEST']._serialized_start=84
  _globals['_DECIDEALERTREQUEST']._serialized_end=195
  _globals['_DECIDEALERTREPLY']._serialized_start=198
  _globals['_DECIDEALERTREPLY']._serialized_end=382
  _globals['_ALERTDECISIONSERVICE']._serialized_start=610
  _globals['_ALERTDECISIONSERVICE']._serialized_end=723
# @@protoc_insertion_point(module_scope)
