\set ON_ERROR_STOP on
REVOKE CONNECT ON DATABASE auditdb FROM PUBLIC;
GRANT CONNECT ON DATABASE auditdb TO audit_owner;
GRANT CONNECT ON DATABASE auditdb TO audit_app;
REVOKE CONNECT ON DATABASE postgres FROM PUBLIC;
