# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: alert.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'alert.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61lert.proto\x12\x11theftdetection.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0c\x63ommon.proto\"\x8f\x03\n\x05\x41lert\x12\x10\n\x08\x61lert_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\x03\x12\x13\n\x0b\x66rame_index\x18\x03 \x01(\x05\x12\x11\n\ttimestamp\x18\x04 \x01(\t\x12\x16\n\tcamera_id\x18\x05 \x01(\tH\x00\x88\x01\x01\x12\'\n\x06person\x18\x06 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\'\n\x06object\x18\x07 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x10\n\x08severity\x18\x08 \x01(\t\x12\x1a\n\rsnapshot_path\x18\t \x01(\tH\x01\x88\x01\x01\x12\x17\n\nalert_type\x18\n \x01(\tH\x02\x88\x01\x01\x12.\n\tkeypoints\x18\x0b \x03(\x0b\x32\x1b.theftdetection.v1.Keypoint\x12\x18\n\x0btorso_angle\x18\x0c \x01(\x02H\x03\x88\x01\x01\x42\x0c\n\n_camera_idB\x10\n\x0e_snapshot_pathB\r\n\x0b_alert_typeB\x0e\n\x0c_torso_angle\"m\n\x0eSendAlertReply\x12)\n\x06status\x18\x01 \x01(\x0e\x32\x19.theftdetection.v1.Status\x12\x30\n\x0c\x64\x65livered_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp*a\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x13\n\x0fSTATUS_ACCEPTED\x10\x01\x12\x17\n\x13STATUS_RATE_LIMITED\x10\x02\x12\x11\n\rSTATUS_FAILED\x10\x03\x32X\n\x0c\x41lertService\x12H\n\tSendAlert\x12\x18.theftdetection.v1.Alert\x1a!.theftdetection.v1.SendAlertReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'alert_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUS']._serialized_start=624
  _globals['_STATUS']._serialized_end=721
  _globals['_ALERT']._serialized_start=112
  _globals['_ALERT']._serialized_end=511
  _globals['_SENDALERTREPLY']._serialized_start=513
  _globals['_SENDALERTREPLY']._serialized_end=622
  _globals['_ALERTSERVICE']._serialized_start=723
  _globals['_ALERTSERVICE']._serialized_end=811
# @@protoc_insertion_point(module_scope)
