# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import presence_pb2 as presence__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in presence_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PresenceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamPresence = channel.stream_stream(
                '/theftdetection.v1.PresenceService/StreamPresence',
                request_serializer=presence__pb2.PresenceEvent.SerializeToString,
                response_deserializer=presence__pb2.PresenceAck.FromString,
                _registered_method=True)


class PresenceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamPresence(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PresenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamPresence': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamPresence,
                    request_deserializer=presence__pb2.PresenceEvent.FromString,
                    response_serializer=presence__pb2.PresenceAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'theftdetection.v1.PresenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('theftdetection.v1.PresenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PresenceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamPresence(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/theftdetection.v1.PresenceService/StreamPresence',
            presence__pb2.PresenceEvent.SerializeToString,
            presence__pb2.PresenceAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
