# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import audit_pb2 as audit__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in audit_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuditServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AppendEvent = channel.unary_unary(
                '/theftdetection.v1.AuditService/AppendEvent',
                request_serializer=audit__pb2.AuditEvent.SerializeToString,
                response_deserializer=audit__pb2.AppendEventReply.FromString,
                _registered_method=True)
        self.QueryEvents = channel.unary_unary(
                '/theftdetection.v1.AuditService/QueryEvents',
                request_serializer=audit__pb2.QueryEventsRequest.SerializeToString,
                response_deserializer=audit__pb2.QueryEventsReply.FromString,
                _registered_method=True)
        self.VerifyChain = channel.unary_unary(
                '/theftdetection.v1.AuditService/VerifyChain',
                request_serializer=audit__pb2.VerifyChainRequest.SerializeToString,
                response_deserializer=audit__pb2.VerifyChainReply.FromString,
                _registered_method=True)
        self.GetCheckpoint = channel.unary_unary(
                '/theftdetection.v1.AuditService/GetCheckpoint',
                request_serializer=audit__pb2.GetCheckpointRequest.SerializeToString,
                response_deserializer=audit__pb2.GetCheckpointReply.FromString,
                _registered_method=True)
        self.ErasePayloads = channel.unary_unary(
                '/theftdetection.v1.AuditService/ErasePayloads',
                request_serializer=audit__pb2.ErasePayloadsRequest.SerializeToString,
                response_deserializer=audit__pb2.ErasePayloadsReply.FromString,
                _registered_method=True)


class AuditServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AppendEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyChain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCheckpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ErasePayloads(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuditServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AppendEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendEvent,
                    request_deserializer=audit__pb2.AuditEvent.FromString,
                    response_serializer=audit__pb2.AppendEventReply.SerializeToString,
            ),
            'QueryEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryEvents,
                    request_deserializer=audit__pb2.QueryEventsRequest.FromString,
                    response_serializer=audit__pb2.QueryEventsReply.SerializeToString,
            ),
            'VerifyChain': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyChain,
                    request_deserializer=audit__pb2.VerifyChainRequest.FromString,
                    response_serializer=audit__pb2.VerifyChainReply.SerializeToString,
            ),
            'GetCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCheckpoint,
                    request_deserializer=audit__pb2.GetCheckpointRequest.FromString,
                    response_serializer=audit__pb2.GetCheckpointReply.SerializeToString,
            ),
            'ErasePayloads': grpc.unary_unary_rpc_method_handler(
                    servicer.ErasePayloads,
                    request_deserializer=audit__pb2.ErasePayloadsRequest.FromString,
                    response_serializer=audit__pb2.ErasePayloadsReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'theftdetection.v1.AuditService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('theftdetection.v1.AuditService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuditService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AppendEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/theftdetection.v1.AuditService/AppendEvent',
            audit__pb2.AuditEvent.SerializeToString,
            audit__pb2.AppendEventReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/theftdetection.v1.AuditService/QueryEvents',
            audit__pb2.QueryEventsRequest.SerializeToString,
            audit__pb2.QueryEventsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyChain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/theftdetection.v1.AuditService/VerifyChain',
            audit__pb2.VerifyChainRequest.SerializeToString,
            audit__pb2.VerifyChainReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/theftdetection.v1.AuditService/GetCheckpoint',
            audit__pb2.GetCheckpointRequest.SerializeToString,
            audit__pb2.GetCheckpointReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ErasePayloads(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/theftdetection.v1.AuditService/ErasePayloads',
            audit__pb2.ErasePayloadsRequest.SerializeToString,
            audit__pb2.ErasePayloadsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
